namespace MorseRunner.Tui;

public enum TuiActionKind
{
    None,
    InsertCharacter,
    Backspace,
    NextField,
    PreviousField,
    StartPileup,
    StartSingle,
    StartWpx,
    StartHst,
    Stop,
    Pause,
    Resume,
    SendCq,
    SendExchange,
    SendThankYou,
    SendMyCall,
    SendHisCall,
    SendBefore,
    SendQuestion,
    SendNil,
    SendNumberQuestion,
    SendCallAndExchange,
    EnterSendMessage,
    SaveQso,
    LogQso,
    Wipe,
    Abort,
    RitUp,
    RitDown,
    BandwidthUp,
    BandwidthDown,
    SpeedUp,
    SpeedDown,
    NextContest,
    PreviousContest,
    NextRunMode,
    PreviousRunMode,
    NextDuration,
    ToggleQsk,
    ToggleQsb,
    ToggleQrm,
    ToggleQrn,
    ToggleFlutter,
    ToggleLids,
    ToggleSettings,
    ToggleResults,
    ToggleDiagnostics,
    ToggleRecording,
    ExportJson,
    ExportCabrillo,
    OpenRecording,
    IncreaseSetting,
    DecreaseSetting,
    ToggleHelp,
    Quit,
}

public readonly record struct TuiAction(
    TuiActionKind Kind,
    char Character = '\0');
